from enum import Enum

class AgentIntent(str, Enum):
    LIST_ORDERS = "LIST_ORDERS"
    GET_ORDER = "GET_ORDER"
    LIST_TASKS = "LIST_TASKS"
    GET_ORDER_TASKS = "GET_ORDER_TASKS"
    LIST_CUSTOMERS = "LIST_CUSTOMERS"
    GET_OVERVIEW = "GET_OVERVIEW"
    GET_ANALYTICS = "GET_ANALYTICS"
    
    # Writes (Phase 5)
    UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS"
    UPDATE_COMMITMENT_DATE = "UPDATE_COMMITMENT_DATE"
    CONFIRM_ACTION = "CONFIRM_ACTION"
    CANCEL_ACTION = "CANCEL_ACTION"
    
    # System
    UNSUPPORTED = "UNSUPPORTED"
    NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"
