from enum import Enum

class AgentIntent(str, Enum):
    LIST_ORDERS = "LIST_ORDERS"
    GET_ORDER = "GET_ORDER"
    LIST_TASKS = "LIST_TASKS"
    GET_ORDER_TASKS = "GET_ORDER_TASKS"
    LIST_CUSTOMERS = "LIST_CUSTOMERS"
    GET_OVERVIEW = "GET_OVERVIEW"
    GET_ANALYTICS = "GET_ANALYTICS"
    
    # Writes (Phase 5)
    CREATE_ORDER = "CREATE_ORDER"
    UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS"
    UPDATE_COMMITMENT_DATE = "UPDATE_COMMITMENT_DATE"
    UPDATE_ORDER_DESTINATION = "UPDATE_ORDER_DESTINATION"
    CONFIRM_ACTION = "CONFIRM_ACTION"
    CANCEL_ACTION = "CANCEL_ACTION"
    
    # System
    UNSUPPORTED = "UNSUPPORTED"
    NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"
    
    # Navigation
    NAVIGATE_TO_DASHBOARD = "NAVIGATE_TO_DASHBOARD"
    NAVIGATE_TO_ORDERS = "NAVIGATE_TO_ORDERS"
    NAVIGATE_TO_TASKS = "NAVIGATE_TO_TASKS"
    NAVIGATE_TO_ANALYTICS = "NAVIGATE_TO_ANALYTICS"
    NAVIGATE_TO_CUSTOMERS = "NAVIGATE_TO_CUSTOMERS"
    NAVIGATE_TO_COMMAND_CENTER = "NAVIGATE_TO_COMMAND_CENTER"
